/**
 * @file triplet_store.hpp
 * @brief C++ relation triplet store.
 *
 * Maintains an in-memory set of (subject, predicate, object) triples
 * together with three hash-map indexes for O(1) average-case queries by
 * subject, predicate, or object.  This is the authoritative source of
 * truth for all links between entities in the vibe-req graph model (see
 * design doc section 5).
 *
 * All callers should use this C++ header directly.
 */

#pragma once

#include <cstddef>
#include <optional>
#include <string>
#include <unordered_map>
#include <vector>

namespace vibe {

/** Stable numeric identifier for a triple. */
using TripleId = std::size_t;

/** Sentinel returned when an operation does not produce a valid ID. */
static constexpr TripleId INVALID_TRIPLE_ID = static_cast<TripleId>(-1);

/** A single relation record. */
struct Triple {
    TripleId    id;        /**< Stable store-assigned identifier. */
    std::string subject;   /**< Subject entity ID (e.g. "REQ-SW-001"). */
    std::string predicate; /**< Relation name (e.g. "derives-from"). */
    std::string object;    /**< Object entity ID or artefact path. */
    bool        inferred;  /**< True if synthetically generated by inverse inference; false if user-declared. */
};

/**
 * In-memory triplet store backed by STL containers.
 *
 * ## Design invariants
 *
 * 1. The three index maps (@c by_subject_, @c by_object_, @c by_predicate_)
 *    always reflect exactly the set of active (non-nullopt) entries in
 *    @c triples_.  Removed entries have their slot set to @c std::nullopt
 *    and their ID is simultaneously removed from all three index vectors,
 *    so index vectors never contain dead (nullopt) IDs.
 *
 * 2. @c triples_ uses slot-based storage: removing a triple leaves a
 *    @c std::nullopt gap.  In high add/remove churn the number of dead slots
 *    can exceed the number of active triples, wasting memory and making
 *    @c find_all() traverse tombstones needlessly.
 *
 * 3. **Lazy compaction** automatically reclaims dead slots: whenever the
 *    number of dead slots (@c dead_count_) reaches the auto-compact threshold
 *    (@c k_compact_threshold dead slots and at least as many dead as alive),
 *    @c compact() is called implicitly after the removal that crossed the
 *    threshold.  Callers may also invoke @c compact() explicitly at any time.
 *
 * 4. @c compact() reassigns consecutive IDs starting from 0.  Any
 *    @c TripleId obtained before a compaction must be considered invalid
 *    afterwards; do not hold @c TripleId values across a @c compact() call.
 */
class TripletStore {
public:
    TripletStore() = default;

    /**
     * Add a (subject, predicate, object) triple.
     * @return  The new triple's stable ID, or INVALID_TRIPLE_ID if an
     *          identical triple already exists.
     */
    TripleId add(const std::string &subject,
                 const std::string &predicate,
                 const std::string &object);

    /**
     * Add a synthetic (inferred) triple.  The triple is marked with
     * @c inferred == true so reporters and validators can distinguish it
     * from user-declared ones.
     *
     * An exact duplicate (same subject, predicate, object, regardless of
     * the inferred flag) is rejected.
     *
     * @return  The new triple's stable ID, or INVALID_TRIPLE_ID if an
     *          identical triple already exists.
     */
    TripleId add_inferred(const std::string &subject,
                          const std::string &predicate,
                          const std::string &object);

    /**
     * Remove a triple by ID.
     * @return  @c true if the triple was found and removed.
     */
    bool remove(TripleId id);

    /**
     * Remove all triples whose subject equals @p subject.
     * @return  Number of triples actually removed.
     */
    std::size_t remove_by_subject(const std::string &subject);

    /**
     * Remove all triples whose object equals @p object.
     * @return  Number of triples actually removed.
     */
    std::size_t remove_by_object(const std::string &object);

    /**
     * Remove all triples whose predicate equals @p predicate.
     * @return  Number of triples actually removed.
     */
    std::size_t remove_by_predicate(const std::string &predicate);

    /** Remove all triples and reset all indexes. */
    void clear() noexcept;

    /**
     * Compact the store by removing dead (nullopt) slots from @c triples_
     * and reassigning consecutive IDs starting from 0.  All three index maps
     * are rebuilt to reflect the new IDs.
     *
     * After this call @c slot_count() == @c count().  Any @c TripleId
     * obtained before this call must be considered invalid.
     *
     * This is called automatically (lazy compaction) when the number of dead
     * slots reaches the built-in threshold; callers may also invoke it
     * explicitly, e.g. after a bulk-remove pass.
     *
     * @return  Number of dead slots reclaimed.
     */
    std::size_t compact();

    /**
     * For every user-declared triple (A, rel, B) where @c rel has a known
     * inverse @c inv(rel) in the built-in relation-pair registry, add a
     * synthetic triple (B, inv(rel), A) marked as inferred — unless an
     * identical triple already exists.
     *
     * Unknown or custom relation names are silently skipped (Option C
     * fallback as described in OPEN_QUESTIONS.md).
     *
     * @return  Number of synthetic triples added.
     */
    std::size_t infer_inverses();

    /**
     * Return a pointer to a triple by ID.
     * @return  Pointer into the store (valid until the next mutation), or
     *          @c nullptr if the ID is unknown or has been removed.
     */
    const Triple *get(TripleId id) const noexcept;

    /**
     * Find all triples with the given subject.
     * Returned pointers are valid until the next mutation.
     */
    std::vector<const Triple *> find_by_subject(const std::string &subject) const;

    /**
     * Find all triples with the given object.
     * Returned pointers are valid until the next mutation.
     */
    std::vector<const Triple *> find_by_object(const std::string &object) const;

    /**
     * Find all triples with the given predicate.
     * Returned pointers are valid until the next mutation.
     */
    std::vector<const Triple *> find_by_predicate(const std::string &predicate) const;

    /**
     * Return all active triples.
     * Returned pointers are valid until the next mutation.
     */
    std::vector<const Triple *> find_all() const;

    /** Number of active (non-removed) triples. */
    std::size_t count() const noexcept { return count_; }

    /**
     * Total number of allocated slots in @c triples_, including dead
     * (nullopt) slots left by previous removals.
     *
     * @c slot_count() - @c count() gives the number of dead slots that a
     * future @c compact() call would reclaim.  After a @c compact() call,
     * @c slot_count() == @c count().
     */
    std::size_t slot_count() const noexcept { return triples_.size(); }

private:
    /** Slot-based storage; removed entries become std::nullopt. */
    std::vector<std::optional<Triple>> triples_;

    /** Indexes: map key -> vector of TripleId slots. */
    std::unordered_map<std::string, std::vector<TripleId>> by_subject_;
    std::unordered_map<std::string, std::vector<TripleId>> by_object_;
    std::unordered_map<std::string, std::vector<TripleId>> by_predicate_;

    /** Cached count of active triples. */
    std::size_t count_{0};

    /** Number of nullopt (dead) slots currently in @c triples_. */
    std::size_t dead_count_{0};

    /**
     * Minimum number of dead slots required before auto-compaction fires.
     * Keeps tiny stores from compacting on every single removal.
     */
    static constexpr std::size_t k_compact_threshold = 16;

    /** Trigger compact() if the lazy-compaction threshold has been reached. */
    void maybe_compact();

    /** Remove @p id from an index entry; erase the entry if it becomes empty. */
    static void index_remove(
        std::unordered_map<std::string, std::vector<TripleId>> &idx,
        const std::string &key,
        TripleId id);
};

} // namespace vibe
